### ISSUE TITLE
Bioconda recipe

### ISSUE THREAD

**Issue by gbouras13** [althonos/pyrodigal-gv#3]
When you get a minute, would you be able to add a `pyrodigal-gv` recipe to bioconda? 

George

**Comment by althonos** [comment]
Going on here but we are facing a weird bug: https://github.com/bioconda/bioconda-recipes/pull/43121

**Comment by althonos** [comment]
Going on here but we are facing a weird bug: https://github.com/bioconda/bioconda-recipes/pull/43121

**Comment by althonos** [comment]
Solved with `v0.2.0`.
